#!/bin/bash

# shellcheck disable=SC1091
source hooks/env

BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
VCS_URL="https://github.com/Dwolla/jenkins-agent-docker-kaniko"

docker build \
	--build-arg VCS_REF="$GIT_SHA1" \
	--build-arg VCS_URL="$VCS_URL" \
	--build-arg BUILD_DATE="$BUILD_DATE" \
	--build-arg VERSION="$GIT_SHA1" \
	-t "$IMAGE_NAME" .
